#!/usr/bin/env node
// Compile vendored frontend skill .md files into a generated TS defaults module.
// Pure helpers are exported for tests; main() runs only on direct invocation.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const FRONTEND_SRC = path.join(REPO_ROOT, "vendor", "skills", "frontend");
const OUT_FILE = path.join(REPO_ROOT, "src", "scrum", "frontend-skill-defaults.generated.ts");

function walkFiles(dir) {
  const files = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) files.push(...walkFiles(p));
    else if (e.isFile()) files.push(p);
  }
  return files;
}

/** Walk srcDir; return [{ name, content, owner_role }] for every skill + shared file. */
export function compileSkills(srcDir) {
  const out = [];
  if (!fs.existsSync(srcDir)) return out;
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dirPath = path.join(srcDir, entry.name);
    if (entry.name === "_shared") {
      for (const f of walkFiles(dirPath)) {
        const rel = path.relative(dirPath, f).split(path.sep).join("/");
        out.push({ name: `fe:_shared/${rel}`, content: fs.readFileSync(f, "utf-8"), owner_role: "fe-engineer" });
      }
      continue;
    }
    const skillFile = path.join(dirPath, "SKILL.md");
    if (fs.existsSync(skillFile)) {
      out.push({ name: `fe:${entry.name}`, content: fs.readFileSync(skillFile, "utf-8"), owner_role: "fe-engineer" });
    }
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

/** Render the generated TS module. JSON.stringify yields valid TS for the array literal. */
export function renderModule(skills) {
  return (
    `// AUTO-GENERATED by scripts/compile-skills.mjs — do not edit by hand.\n` +
    `import type { SkillDefault } from "./defaults.js";\n\n` +
    `export const FRONTEND_SKILL_DEFAULTS: SkillDefault[] = ${JSON.stringify(skills, null, 2)};\n`
  );
}

function main() {
  const skills = compileSkills(FRONTEND_SRC);
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, renderModule(skills));
  console.log(`Compiled ${skills.length} frontend skill entries → ${path.relative(REPO_ROOT, OUT_FILE)}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
